[package]
name = "bot-md-vaccinator"
version = "1.0.0"
edition = "2018"

[dependencies]
rand = "0.8.0"
log = "0.4"
env_logger = "0.8.3"
chrono = "0.4"
yaml-rust = "0.4"
serde_json = "1.0"
urlencoding = "1.3.3"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }
